Install jsbsim in simulation container
PX4/containers pull request #276
Opened 2020-08-28 07:53 UTC by Jaeyoung-Lim

This installs [jsbsim](https://github.com/JSBSim-Team/jsbsim) in the bionic simulation container.

This will enable build/SITL testing on JSBSim

The deb package is ~2.8MB

2020-08-28 07:55 UTC, TSC21 commented
Any reason to not adding this to the Focal one as well? We should start to target Focal as the development platform, not Bionic.

2020-08-28 07:55 UTC, TSC21 requested changes
Please add it to Focal as well.

2020-08-28 08:24 UTC, Jaeyoung-Lim commented
@TSC21 There is no release for focal and I tried installing the same package on focal and it didn't work

2020-08-28 08:36 UTC, TSC21 commented
> @TSC21 There is no release for focal and I tried installing the same package on focal and it didn't work

That doesn't sound good. Can you report this on their repo?

2020-09-05 20:12 UTC, Jaeyoung-Lim commented
JSBSim is now releasing deb packages for Ubuntu 20.04 after https://github.com/JSBSim-Team/jsbsim/pull/317

Therefore I added it to the Ubuntu focal container too

2020-09-10 07:57 UTC, TSC21 approved these changes

2020-09-10 07:57 UTC, merged