Update base container for ros melodic/noetic
PX4/containers pull request #279
Opened 2020-10-13 10:35 UTC by Jaeyoung-Lim

**Problem Description**
While trying to [add catkin build tests](https://github.com/Auterion/px4-jsbsim-bridge/pull/20) to the PX4/px4-jsbsim-bridge, catkin build tests wouldn't pass since jsbsim wasn't installed inside the container.

2020-10-13 12:12 UTC, TSC21 requested changes

2020-10-13 12:12 UTC, TSC21 commented on docker/Dockerfile_ros-melodic
> +FROM px4io/px4-dev-simulation-bionic:2020-09-14
Let's put today's date on this. As soon as we merge this I will tag this and release it.

2020-10-13 12:12 UTC, TSC21 commented on docker/Dockerfile_ros-noetic
> +FROM px4io/px4-dev-simulation-focal:2020-09-14
Same here.

2020-10-13 12:13 UTC, TSC21 commented
@Jaeyoung-Lim for consistency, please also update the tags on all the other containers as well. Thanks!

2020-10-18 23:48 UTC, Jaeyoung-Lim commented
@TSC21 Would it make sense to change it to `latest` ?

2020-10-20 07:28 UTC, TSC21 commented
> @TSC21 Would it make sense to change it to `latest` ?

Not really. This should be controlled.

2020-10-20 13:30 UTC, TSC21 approved these changes

2020-10-20 13:56 UTC, merged